name: satellite-analysis
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy
  - pandas
  - xarray
  - netcdf4
  - h5netcdf
  - h5py
  - dask
  - scipy
  - matplotlib
  - cartopy
  - shapely
  - pyproj
  - geopandas
  - fiona
  - rasterio
  - pyyaml
  - tqdm
  - jupyterlab
  - ipykernel
  - pip

